### ISSUE TITLE
No tab title for CLI guide 

### ISSUE THREAD

**Issue by mattreid** [redhat-appstudio/docs.appstudio.io#139]
When I view https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/getting-started/getting_started_in_cli/ in my browser, the tab says "Untitled :: App Studio Documentation". It seems to be missing whatever metadata normally provides the article title there.

When I look at https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/getting-started/get-started/ it shows a title.

Perhaps because the CLI guide starts with an h2 instead of an h1?

**Comment by gtrivedi88** [comment]
@mattreid This issue is fixed. Please review.
