### ISSUE TITLE
[Doc]: Update instruction of how to "add Integration Tests"

### ISSUE THREAD

**Issue by zdtsw** [redhat-appstudio/docs.appstudio.io#144]
From doc: https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/testing_applications/proc_adding_an_integration_test/
I cannot connect these steps from what I see in my "Add integration test" tab.

What I am asked to fill in from UI :
- Integration test name
- Image bundle
- Pipeline to run

I think the documentation is asking to point to a GitHub repo which has a Tekton Pipeline yaml resides there, but the UI requires a bundle image and must have layer of Pipeline in it.

**Comment by gtrivedi88** [comment]
@Chr1st1anSears Your suggestions on this, please!

**Comment by Chr1st1anSears** [comment]
@zdtsw please try adding an integration test again--the UI has changed and the instructions on that doc are now accurate.

**Comment by zdtsw** [comment]
I have verified with the latest documentation from above link which matches what I've seen in my cluster. 

Some improvement may be good to have, e.g how to define testcase, it requires a yaml file etc.
