### ISSUE TITLE
Cloning procedure feedback

### ISSUE THREAD

**Issue by mattreid** [redhat-appstudio/docs.appstudio.io#220]
Apologies I didn't get to a review of the PR yesterday, but taking a look at https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/managing-applications/proc-managing_applications/ I have a couple things I wanted to mention.

The Prerequisite section for "Cloning applications to a dedicated or all workspaces" doesn't mention they should already have the desired target workspace created and ready before running the export command.

The section header includes "or all workspaces", which it used to mention in a previous iteration, but we weren't sure if there was a use case for that, and looks like that procedure was removed. Should the header be updated to remove "or all", since it only covers exporting to a single destination workspace?

In the next section, the command example still includes the sample "build" as the app name. Could that be updated to match the first section, and use a variable format (like <name_of_your_application>)?

**Comment by gtrivedi88** [comment]
Thank you so much for your time and help, @mattreid 
1. Added a prerequisite
2. Updated the title and removed "or all workspaces".
3. build is replaced with <name_of_your_application>

**Comment by gtrivedi88** [comment]
Closing this issue as all the comments are addressed and got approval here - https://redhat-internal.slack.com/archives/C066J3DC9GT/p1700583493359649
